/* eslint-disable @next/next/no-img-element */
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ht9kOpsb9zz
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Input } from "@/components/ui/input";

export function chat() {
	return (
		<div className="relative h-screen w-full">
			<div className="absolute inset-0 bg-gray-800 bg-opacity-75 flex items-center justify-center">
				<div className="bg-white dark:bg-gray-800 rounded-none shadow-xl p-10">
					<div className="flex justify-end">
						<Button className="text-white bg-red-500 hover:bg-red-700 font-bold w-5 h-5 rounded-none">
							X
						</Button>
					</div>
					<h2 className="text-2xl font-bold mb-8 text-center dark:text-white">
						Welcome to our Chat App
					</h2>
					<div className="flex flex-col items-center justify-between space-y-4">
						<img
							alt="Logo 1"
							height="100"
							src="/placeholder.svg"
							style={{
								aspectRatio: "100/100",
								objectFit: "cover",
							}}
							width="100"
						/>
						<img
							alt="Logo 2"
							height="100"
							src="/placeholder.svg"
							style={{
								aspectRatio: "100/100",
								objectFit: "cover",
							}}
							width="100"
						/>
						<Button className="text-white bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded-none">
							Start Chatting
						</Button>
					</div>
				</div>
			</div>
			<div className="grid h-screen w-full grid-cols-[280px_1fr]">
				<div className="border-r bg-zinc-100/40 dark:bg-zinc-800/40 overflow-auto">
					<div className="px-4 py-2">
						<Button className="w-full text-white bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded-none">
							Neue Anfrage
						</Button>
					</div>
					<nav className="grid items-start px-4 text-sm font-medium py-6">
						<Link
							className="flex items-center gap-3 px-3 py-2 text-zinc-500 transition-all hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50"
							href="#"
						>
							Kontakt
						</Link>
						<Link
							className="flex items-center gap-3 px-3 py-2 text-zinc-500 transition-all hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50"
							href="#"
						>
							Quellcode
						</Link>
						<Link
							className="flex items-center gap-3 px-3 py-2 text-zinc-500 transition-all hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50"
							href="#"
						>
							Datenschutz
						</Link>
						<Link
							className="flex items-center gap-3 px-3 py-2 text-zinc-500 transition-all hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50"
							href="#"
						>
							Impressum
						</Link>
					</nav>
				</div>
				<div className="flex flex-col justify-between">
					<div className="flex flex-col gap-4 p-6 flex-1 overflow-auto" />
					<div className="flex flex-col px-6 py-4 space-y-4">
						<h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-50">
							Example Queries:
						</h3>
						<div className="flex flex-col space-y-2">
							<div className="bg-zinc-100 dark:bg-zinc-700 p-2 text-sm text-zinc-600 dark:text-zinc-400 w-1/2 mx-auto">
								- What's the weather like?
							</div>
							<div className="bg-zinc-100 dark:bg-zinc-700 p-2 text-sm text-zinc-600 dark:text-zinc-400 w-1/2 mx-auto">
								- Set a reminder for my meeting.
							</div>
							<div className="bg-zinc-100 dark:bg-zinc-700 p-2 text-sm text-zinc-600 dark:text-zinc-400 w-1/2 mx-auto">
								- Tell me a joke.
							</div>
							<div className="bg-zinc-100 dark:bg-zinc-700 p-2 text-sm text-zinc-600 dark:text-zinc-400 w-1/2 mx-auto">
								- Your submitted question here.
							</div>
						</div>
						<div className="relative w-1/2 mx-auto mt-4 flex">
							<Input
								className="w-full px-3"
								placeholder="Type a message..."
								type="text"
							/>
							<Button
								className="ml-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-none"
								type="submit"
							>
								Submit
							</Button>
						</div>
					</div>
					<div className="px-6 py-4 border-t flex justify-between items-center">
						<img
							alt="Logo 1"
							height="24"
							src="/placeholder.svg"
							style={{
								aspectRatio: "100/24",
								objectFit: "cover",
							}}
							width="100"
						/>
						<img
							alt="Logo 2"
							height="24"
							src="/placeholder.svg"
							style={{
								aspectRatio: "100/24",
								objectFit: "cover",
							}}
							width="100"
						/>
						<img
							alt="Logo 3"
							height="24"
							src="/placeholder.svg"
							style={{
								aspectRatio: "100/24",
								objectFit: "cover",
							}}
							width="100"
						/>
					</div>
				</div>
			</div>
		</div>
	);
}
