/* eslint-disable @next/next/no-img-element */
"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/os3Im0Kjb6V
 */
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import { Link } from "./Link";
import { cn } from "@/lib/utils";

export function SplashScreen({
	open,
	setOpen,
}: {
	open: boolean;
	setOpen: React.Dispatch<React.SetStateAction<boolean>>;
}) {
	return (
		<Dialog open={open} onOpenChange={setOpen}>
			<DialogContent className=" bg-white dark:bg-gray-800 shadow-lg  max-w-xl mx-auto px-6 md:px-8 py-4 md:py-6 z-50 max-h-screen overflow-y-auto">
				<DialogHeader className="flex">
					<DialogTitle className="py-3 text-left">
						<span className="font-normal text-2xl">
							KI-Assistent für Schriftliche Anfragen{" "}
							<br className="hidden md:inline" />
							und Rote Nummern
						</span>
					</DialogTitle>
				</DialogHeader>
				<div className="space-y-3 text-base">
					<p>
						Dieser Prototyp durchsucht die Schriftlichen Anfragen und die
						Hauptausschussprotokolle (&quot;Rote Nummern&quot;) der Wahlperiode
						19 des Berliner Abgeordnetenhauses und erstellt anhand eines Large
						Language Models Vorlagen für die Beantwortung der gestellten Frage.
						Die Quellen sind auf{" "}
						<Link href="https://www.parlament-berlin.de/dokumente">
							parlament-berlin.de/dokumente
						</Link>{" "}
						zu finden.
					</p>
					<p>
						Bitte beachten Sie, dass die generierten Antworten zwar aus
						offiziellen Dokumenten erstellt wurden, aber keine verbindliche
						Antwort darstellen. Aktuelle KI-Sprachmodelle können zuweilen
						Informationen inkorrekt aufbereiten. Wir empfehlen, die verlinkten
						Quellenangaben zu überprüfen.
					</p>
					<p>Viel Spaß bei der Recherche!</p>
				</div>
				<div className="flex justify-start mt-4 gap-x-8 gap-y-4 flex-wrap">
					<a
						href="https://citylab-berlin.org/de/start/"
						target="_blank"
						rel="noreferrer"
						className={cn(
							`opacity-100 transition-opacity hover:opacity-50`,
							`focus:outline-none focus-visible:ring-2 focus-visible:rounded`,
							`focus-visible:ring-blue-900 focus-visible:ring-offset-8`,
							`focus-visible:ring-offset-white`,
						)}
					>
						<img
							className="h-7"
							alt="Logo CityLAB Berlin"
							src="https://logos.citylab-berlin.org/logo-citylab-berlin-outline.svg"
						/>
					</a>
					<a
						href="https://technologiestiftung-berlin.de/"
						target="_blank"
						rel="noreferrer"
						className={cn(
							`opacity-100 transition-opacity hover:opacity-50`,
							`focus:outline-none focus-visible:ring-2 focus-visible:rounded`,
							`focus-visible:ring-blue-900 focus-visible:ring-offset-8`,
							`focus-visible:ring-offset-white`,
						)}
					>
						<img
							className="h-7"
							alt="Logo der Technologiestiftung Berlin"
							src="https://logos.citylab-berlin.org/logo-tsb-outline.svg"
						/>
					</a>
					<a
						href="https://www.berlin.de/senatskanzlei/"
						target="_blank"
						rel="noreferrer"
						className={cn(
							`opacity-100 transition-opacity hover:opacity-50`,
							`focus:outline-none focus-visible:ring-2 focus-visible:rounded`,
							`focus-visible:ring-blue-900 focus-visible:ring-offset-8`,
							`focus-visible:ring-offset-white`,
						)}
					>
						<img
							className="h-7"
							alt="Logo des Regierenden Bürgermeisters von Berlin und der Senatskanzlei"
							src="https://logos.citylab-berlin.org/logo-senatskanzlei-buergermeister-horizontal.svg"
						/>
					</a>
				</div>
				<div className="flex justify-start gap-x-6 gap-y-3 mt-4 flex-wrap">
					<Link className="text-sm" href="https://citylab-berlin.org/de/start/">
						Kontakt
					</Link>
					<Link
						className="text-sm"
						href="https://github.com/technologiestiftung/ki-anfragen-frontend"
					>
						Quellcode
					</Link>
					<Link
						className="text-sm"
						href="https://citylab-berlin.org/de/data-privacy/"
					>
						Datenschutz
					</Link>
					<Link
						className="text-sm"
						href="https://citylab-berlin.org/de/imprint/"
					>
						Impressum
					</Link>
				</div>
			</DialogContent>
		</Dialog>
	);
}
