name: E2E Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-e2e-tests:
    env:
      CI: true
      NEXT_PUBLIC_PARLA_API_URL: http://localhost:8080
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run start &
      - run: npx playwright install --with-deps
      - run: npx playwright test
